MOvie_TP3/Models/Parent.cs
using MessagePack;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace TP2.Models
{
    public class Parent
    {
        [System.ComponentModel.DataAnnotations.Key]
        public int Id { get; set; }

        [DisplayName("NameStatut")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "{0} doit être rempli.")]
        [StringLength(20, MinimumLength = 2, ErrorMessage = "Le champ {0} demande un minimum de {1} et maximum de {2}.")]
        public string Nom { get; set; }

        [DisplayName("Image")]

        public string ImageURL { get; set; }

        [DisplayName("Description")]

        public string Description { get; set; }
        //public List<ParentEnfant> ParentEnfant { get; set; }
        //public Parent()
        //{
        //    Enfants = new List<Enfant>();
        //}
        public bool IsDisponible { get; set; } = true;
        public List<Enfant> Enfants { get; set; }



    }
}

MOvie_TP3/Controllers/ParentController.cs
using BW5_ExamenFinalReprise.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.EntityFrameworkCore;
using TP2.Models;
using TP2.Models.Data;
using TP2.Services;
using TP2.Utility;
using TP2.ViewModels;

namespace TP2.Controllers
{
    public class ParentsController : Controller
    {

        //private TPDbContext _baseDonnees { get; set; }


        private IParentServices _serviceP;
        private IEnfantServices _serviceE;

        ////public ParentsController(TPDbContext baseDonnees)
        //{
        //    _baseDonnees = baseDonnees;
        //}

        public ParentsController(IParentServices serviceP, IEnfantServices serviceE)
        {
           _serviceP = serviceP;
            _serviceE = serviceE;
            //_baseDonnees = baseDonnees;

        }

        // GET: ParentsControllers
        public async Task<IActionResult> Index()
        {
            //List<Parent> parentsList = await _baseDonnees.Parents.ToListAsync();
            List<Parent> parentsList = (List<Parent>) await _serviceP.GetAllAsync();

            return View(parentsList);
        }

        // GET: ParentsControllers/Details/5
        public async Task<IActionResult> Details(int id)
        {
            //var parentsDetails = _baseDonnees.Enfants.Where(x => x.IdParent == id);
            //ParentVM parentVM = new()
            //{
            //    parent = new(),
            //    EnfantList = parentsDetails.ToList(),
            //    EnfantCount = parentsDetails.Count()
            //};

            //parentVM.parent = await _baseDonnees.Parents.FirstOrDefaultAsync(z => z.Id == id);
            //return View(parentVM);

            var enfant = await _serviceE.GetAllByParentAsync(id);

            ParentVM parentVm = new()
            {
                parent = new(),
                EnfantList = enfant,
                EnfantCount = enfant.Count(),
              
            };

            parentVm.parent = await _serviceP.GetByIdAsync(id);
            return View(parentVm);
        }

        // GET: ParentsControllers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ParentsControllers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Parent parent)
        {
            //if (ModelState.IsValid)
            //{
            //    await _baseDonnees.Parents.AddAsync(parent);
            //    await _baseDonnees.SaveChangesAsync();

            //    TempData[AppConstants.Success] = $"{parent.Nom} le statut a été ajouté";
            //    return this.RedirectToAction("Index");

            //}
            //return this.View(parent);

            if (ModelState.IsValid)
            {
                await _serviceP.CreateAsync(parent);
               
                return this.RedirectToAction("Index", parent);

            }
            return this.View(parent);
        }

        // GET: ParentsController/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            //Parent parent = await _baseDonnees.Parents.FindAsync(id);
            //return View(parent);
            Parent? parent = await _serviceP.GetByIdAsync(id);

            return View("Edit", parent);
        }

        // POST: ParentsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Parent parent)
        {
            //    if (ModelState.IsValid)
            //    {
            //        _baseDonnees.Parents.Update(parent);
            //        await _baseDonnees.SaveChangesAsync();
            //        TempData[AppConstants.Success] = $"Statut {parent.Nom} a été modifié";
            //        return this.RedirectToAction("Index", "parents");
            //    }
            //    return View(parent);
            if (ModelState.IsValid)
            {
                await _serviceP.EditAsync(parent);
                return this.RedirectToAction("Index");
            }

            return View("Edit", parent);

        }

        // GET: ParentsControllers/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            //Parent? parent = await _baseDonnees.Parents.FindAsync(id);
            //if (parent == null)
            //{
            //    return View("NonTrouve", "Le statut demandé n'a pas été trouvé!");

            //}
            //return View(parent);

            Parent? parent = await _serviceP.GetByIdAsync(id);
            if (parent == null)
            {
                return NotFound();
            }

            return View("Delete", parent);
        }

        // POST: ParentsControllers/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePost(int id)
        {
            //Parent? parent = await _baseDonnees.Parents.FindAsync(id);
            //if (parent == null)
            //{
            //    return View("NonTrouve", "Le statut demandé n'a pas été trouvé!");

            //}
            //_baseDonnees.Parents.Remove(parent);
            //await _baseDonnees.SaveChangesAsync();
            //TempData[AppConstants.Success] = $"Statut {parent.Nom} a été suprrimé";
            //return RedirectToAction("Index");
            Parent? parent = await _serviceP.GetByIdAsync(id);
            if (parent == null)
            {
                return NotFound();
            }

            await _serviceP.DeleteAsync(id);
            return RedirectToAction("Index");
        }
    }
}

MOvie_TP3/Views/Parents/Create.cshtml
@model Parent
@{

    ViewData["titre"] = @Locals["Create"];

}
<h1>@Locals["Title"]</h1>
<h4>Statut</h4>
<hr />
<div class="row">
    <div class="col-md-10">
        <div class="row p-3 ">
            <form asp-controller="Parents" asp-action="Create" method="post">


                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Nom" class="control-label"></label>
                    </div>
                    <div class="col-8">
                        <input type="text" asp-for="Nom" class="form-control" />
                        <span asp-validation-for="Nom" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Description" class="control-label"></label>
                    </div>
                    <div class="col-8" style="border: solid 1px white">
                        @*<input asp-for="Description" class="form-control" />*@
                        <textarea asp-for="@Model.Description" class="form-control summernote" style="height:300px;"></textarea>

                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="ImageURL" class="control-label"></label>
                    </div>
                    <div class="col-8">
                        <input type="text" asp-for="ImageURL" class="form-control" />
                        <span asp-validation-for="ImageURL" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row  py-2">
                    <div class="col-10 offset-4 row">
                        <div class="col-5">

                            <button type="submit" class="btn btn-success w-100" value="Create"><i class="fas fa-plus-square"></i>&nbsp;&nbsp;@Locals["Create"]</button>


                        </div>
                        <div class="col-5">
                            <a asp-action="Index" class="btn btn-secondary "><i class="fa-solid fa-circle-arrow-left"></i>&nbsp;&nbsp;@Locals["BackToList"]</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    @*<partial name ="_ValidationScriptsPartial"   />*@
    <script>
        $(document).ready(function () { $('.summernote').summernote(); });
    </script>
 }




MOvie_TP3/Views/Parents/Delete.cshtml
@model Parent
@{
    ViewData["titre"] = @Locals["Title"];


}
<h1>@Locals["Title"]</h1>
<form method="post" asp-action="DeletePost">
    <div class="border p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input asp-for="@Model.Id" class="form-control" hidden />
        <div class="form-group row">
            <h2 class="text-info pl-3">Statut</h2>
            <hr />
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-2">
                        <label asp-for="Nom"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Nom" class="form-control" />
                        <span asp-validation-for="Nom" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-2">
                        <label asp-for="Description" class="col-form-label"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row py-2">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <button type="submit" value="Delete" class="btn btn-danger w-100"><i class="fa-solid fa-trash-can"></i>&nbsp;&nbsp;@Locals["Delete"]</button>
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-secondary "><i class="fa-solid fa-circle-arrow-left"></i>&nbsp;&nbsp;@Locals["BackToList"]</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    @*<partial name ="_ValidationScriptsPartial"   />*@

 }



MOvie_TP3/Views/Parents/Details.cshtml
@model ParentVM

@{
    ViewData["Title"] = @Locals["Title"];

}

<h1 style="padding-top:40px">Statut: @Model.parent.Nom</h1>
<h3 style="padding-bottom:30px">@Locals["NbMovie"]: @Model.EnfantCount</h3>

<div class="row">
    @*  POUR CHAQUE ZOMBIE:*@
    @foreach (var item in Model.EnfantList)
    {
        <partial name="_EnfantPartiel" model="item" />
    }
</div>
@* SI AUCUN ZOMBIE ASSOCIÉ*@
@if (Model.EnfantList.Count == 0)
{
    <div class="alert alert-danger">@Locals["Alert"]</div>
}
<div>
    <a class="btn btn-secondary" asp-action="Index">@Locals["BackToList"]</a>
</div>

MOvie_TP3/Views/Parents/Edit.cshtml
@model Parent
@{
    ViewData["titre"] = @Locals["Edit"];


}
<h1>@Locals["Edit"]</h1>
<h4>Statut</h4>
<hr />
<div class="row">
    <div class="col-md-10">
        <div class="row p-3 ">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group row">
                    <input asp-for="@Model.Id" class="form-control" hidden />
                    <div class="col-4">
                        <label asp-for="@Model.Nom" class="control-label"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="@Model.Nom" class="form-control" />
                        <span asp-validation-for="@Model.Nom" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="@Model.Description" class="control-label"></label>
                    </div>
                    <div class="col-8">
                        <textarea asp-for="@Model.Description" class="form-control summernote" style="height:300px;"></textarea>

                        <span asp-validation-for="@Model.Description" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="ImageURL" class="control-label"></label>
                    </div>
                    <div class="col-8">
                        <input type="text" asp-for="ImageURL" class="form-control" />
                        <span asp-validation-for="ImageURL" class="text-danger"></span>
                    </div>
                </div>


                <div class="form-group row  py-2">
                    <div class="col-10 offset-4 row">
                        <div class="col-5">
                            <button type="submit" value="Edit" class="btn btn-info w-100"><i class="fa-solid fa-pen-to-square"></i>&nbsp;&nbsp;@Locals["Edit"]</button>
                        </div>
                        <div class="col-5">
                            <a class="btn btn-secondary " asp-action="Index"><i class="fa-solid fa-circle-arrow-left"></i>&nbsp;&nbsp;@Locals["BackToList"]</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    @*<partial name ="_ValidationScriptsPartial"   />*@
    <script>
        $(document).ready(function () { $('.summernote').summernote(); });
    </script>
 }



MOvie_TP3/Views/Parents/Index.cshtml
@model IEnumerable<Parent>
@{
    //ViewData["titre"] = @Locals["Title"];

}
<div class="list-statut">
</div>    ﻿<div class="container p-3">
    <div class="row pt-4">
        <div class="col-10">
            <h2 class="text-primary">@Locals["Title"]</h2>
        </div>
        <div class="col-2 text-right">
            <a class="btn btn-success" asp-controller="Parents" asp-action="Create">
                <i class="fa-solid fa-plus"></i>&nbsp;&nbsp;@Locals["New"]
            </a>
        </div>
    </div>

    <br /><br />
    <table class="table table-bordered table-striped" style="width:100%">
        <thead class="bg-dark text-white">
            <tr>
                <th>
                    @Locals["Name"]
                </th>
                <th> 
                    Image
                </th>
                <th>
                    Actions
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td width="40%">
                        <a class="btn btn-info" asp-action="Details" asp-route-id="@item.Id">
                            @item.Nom
                        </a>
                    </td>
                    <td width="30%">
                        <a class="" asp-action="Details" asp-route-id="@item.Id">
                        <img src="@item.ImageURL" alt="">
                        </a>
                    </td>
                    <td class="text-center">
                        <div class="w-75 btn-group" role="group">
                            <a class="btn btn-warning mx-2" asp-action="Edit" asp-route-Id="@item.Id">
                                <i class="fa-solid fa-pen-to-square"></i>&nbsp;&nbsp;@Locals["Edit"]
                            </a>
                            <a class="btn btn-danger mx-2" asp-action="Delete" asp-route-Id="@item.Id">
                                <i class="fa-solid fa-trash"></i>&nbsp;&nbsp;@Locals["Delete"]
                            </a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div class="col-5">
        <a asp-action="Index" asp-controller="Home" class="btn btn-secondary "><i class="fa-solid fa-circle-arrow-left"></i>&nbsp;&nbsp;@Locals["BackToList"]</a>
    </div>
</div>



MOvie_TP3/Views/Parents/_EnfantPartiel.cshtml
@model Enfant



<div class="col_movie col-12 col-md-6 col-lg-3" ">
    <div class="card_movie card ">
        <img src="@Model.ImageURL" class="card-img-top" alt="...">
        <p class="name_movie">@Model.Nom</p>
        <div class="desc_movie">
            <p>@Model.Description</p>
        </div>
        <div class="btn_plus_detail">
            <a href="/enfant/detail/@Model.Id"><button class="btn button_todetail">@Locals["MoreDetail"]</button></a>
          

            <a class="btn btn-info mx-2" asp-action="Edit" asp-route-Id="@Model.Id">
                <i class="fa-solid fa-pen-to-square"></i>&nbsp;&nbsp;@Locals["Edit"]
            </a>
            <a class="btn btn-danger mx-2" asp-action="Delete" asp-route-Id="@Model.Id">
                <i class="fa-solid fa-trash"></i>&nbsp;&nbsp;@Locals["Delete"]
            </a>



        </div>
    </div>
</div>